import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'node_modules/visio-cms/dist/lib.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Visio app',
  description: 'Generated by create visio app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
