name: CI

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - name: Install dependencies
      run: npm install

    - name: Run linting and Prettier
      run: |
        npm run format
        npm run lint
